config/routes.rb
Rails.application.routes.draw do
  get '/503', to: 'errors#service_unavailable'
  get '/500', to: 'errors#internal_server_error'

  root 'home#index'
  resources :scrapers
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/scraper.rb
require 'nokogiri'
require 'open-uri'

class Scraper
  PRICE_CSS      = 'div.ellipsized_1iurgbx[data-reactid] span.text_5mbkop-o_O-size_small_1gg2mc-o_O-weight_bold_153t78d-o_O-inline_g86r3e[data-reactid] span[data-reactid]'.freeze
  PAGINATION_CSS = 'ul.buttonList_11hau3k li.buttonContainer_1am0dt a.link_1ko8une'.freeze
  BASE_URL       = 'https://airbnb.com/s/'.freeze
  GUESTS         = '/?guests=2'.freeze
  MONTH          = 30

  def initialize(hash)
    @currency = ''
    @city     = hash[:city]
    @street   = hash[:street]
    @country  = hash[:country]
    @url      = BASE_URL       +
                gsub(@street)  + '--' +
                gsub(@city)    + '--' +
                gsub(@country) +
                GUESTS
  end

  def get_airbnb
    page = Nokogiri::HTML(open(@url, 'User-Agent' => "Ruby/#{RUBY_VERSION}"))

    # Scrape the max number of pages and store in max_page variable
    page_numbers = []
    page.css(PAGINATION_CSS).each do |line|
      page_numbers << line.text
    end
    page_numbers = page_numbers.map(&:to_i)
    max_page     = page_numbers.max

    # Initialize empty arrays
    price_name = []
    price      = []
    name       = []

    # Loop once for every page of search results
    max_page.times do |i|
      # Open search results page
      url  = @url + "?section offset=#{i}"
      page = Nokogiri::HTML(open(url, 'User-Agent' => "Ruby/#{RUBY_VERSION}"))

      # Find all properties (Name - Price)
      page.css(PRICE_CSS).each do |line|
        name << line.text.strip
      end
    end

    # Delete word Price from array
    name -= %w[Price]
    # binding.pry
    # seperate price from name
    name.each do |n|
      price_name << n if name.index(n).even?
    end

    # seperate currency
    currency = price_name[0].chr

    # parse price array from string to integer
    price_name.each do |p|
      p.delete!(currency)
      p.delete!(',') if p.include?(',')
      price << p.to_i
    end

    # calculating average price
    sum_price = price.inject { |sum, p| sum + p }
    count_rooms = price.length
    airbnb_price = sum_price / count_rooms * MONTH

    { currency: currency, price: airbnb_price }
  end

  private

  def gsub(string)
    string.gsub(/\s/, '-')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def service_unavailable
    render json: {
      status: 503,
      error: :service_temporarily_unavailable,
      message: 'Please try again later'
    }, status: 503
  end

  def internal_server_error
    render json: {
      status: 500,
      error: :internal_server_error,
      message: 'Please check your address is correct'
    }, status: 500
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController; end

app/controllers/scrapers_controller.rb
class ScrapersController < ApplicationController
  def new
    @scraper = Scraper.new
  end

  def create
    @scraper = Scraper.new(scraper_params)
    airbnb_price(@scraper)
    render "show"
  end

  private

  def airbnb_price(scraper)
    airbnb        = scraper.get_airbnb
    @airbnb_price = airbnb[:price]
    @currency     = airbnb[:currency]
    @result       = @airbnb_price - long_term_rent(scraper)
  end

  def long_term_rent(scraper)
    params[:scraper][:long_term_rent].to_i
  end

  def scraper_params
    params.require(:scraper).permit(:country, :city, :street, :long_term_rent)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<div>
  <h2>Welcome to Lu-Air!</h2>
  <h4>To estimate your future benefits from airbnb please click below</h4>
  <%= link_to 'Join us', scrapers_path %>
</div

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LuAir</title>
    <%= csrf_meta_tags %>
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=AIzaSyAyrs9of3ZsEffdTYrjtpR70xWQXk1XSiA&libraries=places" %>

    <%= javascript_include_tag "https://use.fontawesome.com/f660b6bdba.js" %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/scrapers/index.html.erb
<div id="locationField">
  <input id="autocomplete" placeholder="Enter your address"
         onFocus="geolocate()" type="text"></input>
</div>

<%= form_for :scraper, method: "post" do |f|%>
  <%= f.label "Street address"%>
  <%= f.text_field :street, placeholder: "Street", id: 'route'  %>
  <%= f.label "City" %>
  <%= f.text_field :city, placeholder: "City", id: 'locality' %>
  <%= f.label "Country"%>
  <%= f.text_field :country, placeholder: "Country", id: 'country'  %>
  <%= f.label "Long-term rent"%>
  <%= f.text_field :long_term_rent  %>
  <%= f.submit("Show") %>
<% end %>


<!--autocomplete HTML-->
<input class="invisible" id="route"></input>
<input class="invisible" id="street_number"></input>
<input class="invisible" id="locality"></input>
<input class="invisible" id="administrative_area_level_1"></input>
<input class="invisible" id="country" ></input>

<!--autocomplete script-->
<script src="app/assets/javascripts/autocomplete.js"></script>
<!--googleapis-->
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAyrs9of3ZsEffdTYrjtpR70xWQXk1XSiA&libraries=places&callback=initAutocomplete"
async defer></script>

app/views/scrapers/show.html.erb
<div>
  <% if @result < 0 %>
    <p>You should better consider long-term rentals!</p>
    <br>
    <%="You monthly loss will be #{@result}#{@currency}"%>
  <% else %>
    <p>Congratulations! Your cooperation with Airbnb will be lucrative!</p>
    <%= "You monthly profit will be #{@result}#{@currency}"%>
  <% end %>
  <br>
  <%= link_to 'Check another address', scrapers_path %>
</div>